<html xmlns="http://www.w3.org/1999/xhtml">

</html>

<style>
    .sk-cont-too {
        text-align: center;
        background-color: rgb(255, 255, 255);
    }

    .footer-menu ul {
        margin: 0;
        list-style: none;
        padding: 0;
        display: flex;
        justify-content: center;

    }

    .footer-menu li {
        padding: 10px
    }

    .divider {
        border-right: 2px solid rgb(139, 87, 87);
        border-left: 2px solid rgb(139, 87, 87);
    }

    .sk-iconos {
        width: 100%;

        background-color: rgba(8, 8, 8, 0.781);
        color: antiquewhite;
        font-size: 3em;
        display: flex;
        justify-content: center;


    }

    .sk-iconos-paraf {
        border-radius: 100%;
        background-color: white;
        color: black;
        width: 63px;
        margin: 6px;

    }
</style>
<div class="sk-cont-too">

    <h1>CONTACTO</h1>
    <h2> Guachene ,Cauca</h2>
    <p> - All rights reserved. Desarrollamos tu eCommerce.</p>
    <p>Contactenos o escribenos <a href="agsoftware.online@gmail.com">agsoftware.online@gmail.com</a></p>



    <p>NIT: 901522730 - 7 </p>


    <p>TEL: 320 777 5771</p>

    <p>Dirección: Guachené CR 7A # 8 -39</p>

    <nav class="footer-menu">
        <ul>
            <li><a href="/Que-ofrecemos">Qué ofrecemos?</a></li>
            <li class="divider"><a href="/Nosotros">Nosotros</li>
            <li><a href="/Nuestros">Nuestros</a></li>

        </ul>
        <div class="sk-iconos">
            <p class="sk-iconos-paraf"> in
        </div>
    </nav>
</div>